Theory and Practice of FEM -- a parametrized Poisson Solver: Step4< dim > Class Template Reference
Step4< dim > Class Template Reference
Public Member Functions
Step4 ()
void run ()
Private Member Functions
void make_grid ()
void setup_system ()
void assemble_system ()
void solve ()
void output_results () const
Private Attributes
Triangulation< dim > triangulation
FE_Q< dim > fe
DoFHandler< dim > dof_handler
SparsityPattern sparsity_pattern
SparseMatrix< double > system_matrix
Vector< double > solution
Vector< double > system_rhs
Detailed Description
template<int dim>
class Step4< dim >
Definition at line 49 of file step-4.cc.
Constructor & Destructor Documentation
Step4()
template<int dim> Step4< dim >::Step4
Definition at line 107 of file step-4.cc.
References triangulation.
Member Function Documentation
assemble_system()
template<int dim> void Step4< dim >::assemble_system private
Definition at line 138 of file step-4.cc.
References Vector< double >::add(), MatrixTools::apply_boundary_values(), cell_matrix(), FEValuesBase< dim, dim >::dof_indices(), VectorTools::interpolate_boundary_values(), FEValuesBase< dim, dim >::JxW(), FEValuesBase< dim, dim >::quadrature_point(), FEValuesBase< dim, dim >::quadrature_point_indices(), FEValues< dim >::reinit(), FEValuesBase< dim, dim >::shape_grad(), FEValuesBase< dim, dim >::shape_value(), update_gradients, update_JxW_values, update_quadrature_points, update_values, and RightHandSide< dim >::value().
make_grid()
template<int dim> void Step4< dim >::make_grid private
Definition at line 113 of file step-4.cc.
References GridGenerator::hyper_cube(), and triangulation.
output_results()
template<int dim> void Step4< dim >::output_results private
Definition at line 200 of file step-4.cc.
References DataOut_DoFData< DoFHandler< dim >, DoFHandler< dim > ::dimension, DoFHandler< dim > ::space_dimension >::add_data_vector(), DataOut_DoFData< DoFHandler< dim >, DoFHandler< dim > ::dimension, DoFHandler< dim > ::space_dimension >::attach_dof_handler(), DataOut< dim >::build_patches(), and DataOutInterface< patch_dim, patch_space_dim >::write_vtk().
run()
template<int dim> void Step4< dim >::run
Definition at line 211 of file step-4.cc.
Referenced by main().
setup_system()
template<int dim> void Step4< dim >::setup_system private
Definition at line 124 of file step-4.cc.
References DoFTools::make_sparsity_pattern().
solve()
template<int dim> void Step4< dim >::solve private
Definition at line 190 of file step-4.cc.
References e(), SolverControl::last_step(), and SolverCG< VectorType >::solve().
Member Data Documentation
dof_handler
template<int dim> DoFHandler<dim> Step4< dim >::dof_handler private
Definition at line 69 of file step-4.cc.
fe
template<int dim> FE_Q<dim> Step4< dim >::fe private
Definition at line 68 of file step-4.cc.
solution
template<int dim> Vector<double> Step4< dim >::solution private
Definition at line 72 of file step-4.cc.
sparsity_pattern
template<int dim> SparsityPattern Step4< dim >::sparsity_pattern private
Definition at line 70 of file step-4.cc.
system_matrix
template<int dim> SparseMatrix<double> Step4< dim >::system_matrix private
Definition at line 71 of file step-4.cc.
system_rhs
template<int dim> Vector<double> Step4< dim >::system_rhs private
Definition at line 73 of file step-4.cc.
triangulation
template<int dim> Triangulation<dim> Step4< dim >::triangulation private
Definition at line 67 of file step-4.cc.
The documentation for this class was generated from the following file:
/github/workspace/source/step-4.cc